# This is only used by ReadTheDocs to ensure the latest node is installed
name: docs
channels:
  - conda-forge
dependencies:
  - nodejs
  - pip:
    - sphinx>2
    - myst_parser
    - sphinx_copybutton
    - sphinx_book_theme
    - sphinx-js